apiVersion: topologies.eda.nokia.com/v1alpha1
kind: NetworkTopology
metadata:
  generateName: try-eda-topology-
  name: try-eda-topology
spec:
  links:
  - endpoints:
    - local:
        interface: ethernet-1-1
        node: leaf1
      remote:
        interface: ethernet-1-1
        node: spine1
      type: interSwitch
    labels:
      eda.nokia.com/role: interSwitch
    name: leaf1-spine1-1
  - endpoints:
    - local:
        interface: ethernet-1-2
        node: leaf1
      remote:
        interface: ethernet-1-2
        node: spine1
      type: interSwitch
    labels:
      eda.nokia.com/role: interSwitch
    name: leaf1-spine1-2
  - endpoints:
    - local:
        interface: ethernet-1-1
        node: leaf2
      remote:
        interface: ethernet-1-3
        node: spine1
      type: interSwitch
    labels:
      eda.nokia.com/role: interSwitch
    name: leaf2-spine1-1
  - endpoints:
    - local:
        interface: ethernet-1-2
        node: leaf2
      remote:
        interface: ethernet-1-4
        node: spine1
      type: interSwitch
    labels:
      eda.nokia.com/role: interSwitch
    name: leaf2-spine1-2
  - encapType: dot1q
    endpoints:
    - local:
        interface: ethernet-1-3
        node: leaf1
      type: edge
    labels:
      eda.nokia.com/role: edge
    name: leaf1-ethernet-1-3
  - encapType: dot1q
    endpoints:
    - local:
        interface: ethernet-1-4
        node: leaf1
      type: edge
    labels:
      eda.nokia.com/role: edge
    name: leaf1-ethernet-1-4
  - encapType: dot1q
    endpoints:
    - local:
        interface: ethernet-1-5
        node: leaf1
      type: edge
    labels:
      eda.nokia.com/role: edge
    name: leaf1-ethernet-1-5
  - encapType: dot1q
    endpoints:
    - local:
        interface: ethernet-1-6
        node: leaf1
      type: edge
    labels:
      eda.nokia.com/role: edge
    name: leaf1-ethernet-1-6
  - encapType: dot1q
    endpoints:
    - local:
        interface: ethernet-1-7
        node: leaf1
      type: edge
    labels:
      eda.nokia.com/role: edge
    name: leaf1-ethernet-1-7
  - encapType: dot1q
    endpoints:
    - local:
        interface: ethernet-1-8
        node: leaf1
      type: edge
    labels:
      eda.nokia.com/role: edge
    name: leaf1-ethernet-1-8
  - encapType: dot1q
    endpoints:
    - local:
        interface: ethernet-1-9
        node: leaf1
      type: edge
    labels:
      eda.nokia.com/role: edge
    name: leaf1-ethernet-1-9
  - encapType: dot1q
    endpoints:
    - local:
        interface: ethernet-1-10
        node: leaf1
      type: edge
    - local:
        interface: ethernet-1-11
        node: leaf1
      type: edge
    labels:
      eda.nokia.com/role: edge
    name: leaf1-e1011
  - encapType: dot1q
    endpoints:
    - local:
        interface: ethernet-1-3
        node: leaf2
      type: edge
    labels:
      eda.nokia.com/role: edge
    name: leaf2-ethernet-1-3
  - encapType: dot1q
    endpoints:
    - local:
        interface: ethernet-1-4
        node: leaf2
      type: edge
    labels:
      eda.nokia.com/role: edge
    name: leaf2-ethernet-1-4
  - encapType: dot1q
    endpoints:
    - local:
        interface: ethernet-1-5
        node: leaf2
      type: edge
    labels:
      eda.nokia.com/role: edge
    name: leaf2-ethernet-1-5
  - encapType: dot1q
    endpoints:
    - local:
        interface: ethernet-1-6
        node: leaf2
      type: edge
    labels:
      eda.nokia.com/role: edge
    name: leaf2-ethernet-1-6
  - encapType: dot1q
    endpoints:
    - local:
        interface: ethernet-1-7
        node: leaf2
      type: edge
    labels:
      eda.nokia.com/role: edge
    name: leaf2-ethernet-1-7
  - encapType: dot1q
    endpoints:
    - local:
        interface: ethernet-1-8
        node: leaf2
      type: edge
    labels:
      eda.nokia.com/role: edge
    name: leaf2-ethernet-1-8
  - encapType: dot1q
    endpoints:
    - local:
        interface: ethernet-1-9
        node: leaf2
      type: edge
    labels:
      eda.nokia.com/role: edge
    name: leaf2-ethernet-1-9
  - encapType: dot1q
    endpoints:
    - local:
        interface: ethernet-1-10
        node: leaf2
      type: edge
    - local:
        interface: ethernet-1-11
        node: leaf2
      type: edge
    labels:
      eda.nokia.com/role: edge
    name: leaf2-e1011
  - encapType: dot1q
    endpoints:
    - local:
        interface: ethernet-1-12
        node: leaf1
      type: edge
    - local:
        interface: ethernet-1-12
        node: leaf2
      type: edge
    labels:
      eda.nokia.com/role: edge
    name: leaf1-2-e1212
  nodes:
  - labels:
      eda.nokia.com/role: leaf
      eda.nokia.com/security-profile: managed
    name: leaf1
    nodeProfile: srlinux-ghcr-25.10.1
    operatingSystem: srl
    platform: 7220 IXR-D3L
    version: 25.10.1
  - labels:
      eda.nokia.com/role: leaf
      eda.nokia.com/security-profile: managed
    name: leaf2
    nodeProfile: srlinux-ghcr-25.10.1
    operatingSystem: srl
    platform: 7220 IXR-D3L
    version: 25.10.1
  - labels:
      eda.nokia.com/role: spine
      eda.nokia.com/security-profile: managed
    name: spine1
    nodeProfile: srlinux-ghcr-25.10.1
    operatingSystem: srl
    platform: 7220 IXR-D5
    version: 25.10.1
  operation: replaceAll
  simulation:
    simNodes:
    - name: testman-default
      type: TestMan
    topology:
    - interface: '*'
      node: '*'
      simNode: testman-default
