---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  ipFamily: dual
  # if you want to expose the kind cluster externally
  # change the API server address from loopback to the desired IP
  # via KIND_API_SERVER_ADDRESS make variable
  apiServerAddress: "127.0.0.1"
nodes:
  - role: control-plane
    # https://kind.sigs.k8s.io/docs/user/configuration/#extra-port-mappings
    extraPortMappings:
      # reserve 32767 node port to expose EDA UI/API HTTPS service over this port
      # the hostPort is overwritten at runtime based on the selected EXT_HTTPS_PORT variable
      - containerPort: 32767
        hostPort: 9443
        listenAddress: "0.0.0.0"
      # reserve 32766 node port to expose EDA gRPC proxy service over this port (for edactl)
      - containerPort: 32766
        hostPort: 51206
        listenAddress: "0.0.0.0"
    # reserve node ports for branched clusters
      - containerPort: 32765
        hostPort: 9501            # branch 1 UI/API
        listenAddress: "0.0.0.0"
      - containerPort: 32764
        hostPort: 9502            # branch 1 GRPC
        listenAddress: "0.0.0.0"
      - containerPort: 32763
        hostPort: 9503            # branch 2 UI/API
        listenAddress: "0.0.0.0"
      - containerPort: 32762
        hostPort: 9504            # branch 2 GRPC
        listenAddress: "0.0.0.0"
      - containerPort: 32761
        hostPort: 9505            # branch 3 UI/API
        listenAddress: "0.0.0.0"
      - containerPort: 32760
        hostPort: 9506            # branch 3 GRPC
        listenAddress: "0.0.0.0"

    # allow longer port-forwarding connection
    # see https://stackoverflow.com/a/48829363
    kubeadmConfigPatches:
      - |
        kind: KubeletConfiguration
        streamingConnectionIdleTimeout: "96h0m0s"
