---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: kind # kpt-set: ${LB_POOL_NAME}
  namespace: metallb-system
spec:
  addresses: # kpt-set: ${LB_IP_POOLS}
  - 172.19.255.0/24
  - fc00:f853:ccd:e793:ffff:ffff:ffff:ffff/120
  avoidBuggyIPs: true
